[package]
name = "example_channel"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
netfn = { workspace = true }
netfn_transport_channel = { workspace = true }
tokio = { workspace = true, features = ["full"] }
