[package]
name = "example_ws"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
netfn = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tungstenite = { workspace = true }
